// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddActedInRelationData, AddActedInRelationErrors, AddActedInRelationResponses, AddDirectorLabelData, AddDirectorLabelErrors, AddDirectorLabelResponses, CreateActorData, CreateActorResponses, DeletePersonData, DeletePersonErrors, DeletePersonResponses, ExpandGraphNodeData, ExpandGraphNodeErrors, ExpandGraphNodeResponses, GetApiDebugBrokenQueryData, GetApiDebugBrokenQueryResponses, GetApiDebugDuplicateGenreData, GetApiDebugDuplicateGenreResponses, GetMovieProfileData, GetMovieProfileErrors, GetMovieProfileResponses, GetMoviesData, GetMoviesResponses, GetPersonProfileData, GetPersonProfileErrors, GetPersonProfileResponses, GetTopMoviesData, GetTopMoviesResponses, HealthData, HealthDbData, HealthDbResponses, HealthResponses, RemoveActedInRelationData, RemoveActedInRelationErrors, RemoveActedInRelationResponses, UpdatePersonData, UpdatePersonErrors, UpdatePersonResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>): RequestResult<HealthDbResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

export const getApiDebugBrokenQuery = <ThrowOnError extends boolean = false>(options?: Options<GetApiDebugBrokenQueryData, ThrowOnError>): RequestResult<GetApiDebugBrokenQueryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiDebugBrokenQueryResponses, unknown, ThrowOnError>({ url: '/api/debug/broken-query', ...options });

export const getApiDebugDuplicateGenre = <ThrowOnError extends boolean = false>(options?: Options<GetApiDebugDuplicateGenreData, ThrowOnError>): RequestResult<GetApiDebugDuplicateGenreResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiDebugDuplicateGenreResponses, unknown, ThrowOnError>({ url: '/api/debug/duplicate-genre', ...options });

export const getTopMovies = <ThrowOnError extends boolean = false>(options?: Options<GetTopMoviesData, ThrowOnError>): RequestResult<GetTopMoviesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTopMoviesResponses, unknown, ThrowOnError>({ url: '/api/movies/top', ...options });

export const getMovieProfile = <ThrowOnError extends boolean = false>(options: Options<GetMovieProfileData, ThrowOnError>): RequestResult<GetMovieProfileResponses, GetMovieProfileErrors, ThrowOnError> => (options.client ?? client).get<GetMovieProfileResponses, GetMovieProfileErrors, ThrowOnError>({ url: '/api/movies/profile', ...options });

export const deletePerson = <ThrowOnError extends boolean = false>(options: Options<DeletePersonData, ThrowOnError>): RequestResult<DeletePersonResponses, DeletePersonErrors, ThrowOnError> => (options.client ?? client).delete<DeletePersonResponses, DeletePersonErrors, ThrowOnError>({ url: '/api/persons/{tmdbId}', ...options });

export const getPersonProfile = <ThrowOnError extends boolean = false>(options: Options<GetPersonProfileData, ThrowOnError>): RequestResult<GetPersonProfileResponses, GetPersonProfileErrors, ThrowOnError> => (options.client ?? client).get<GetPersonProfileResponses, GetPersonProfileErrors, ThrowOnError>({ url: '/api/persons/{tmdbId}', ...options });

export const updatePerson = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonData, ThrowOnError>): RequestResult<UpdatePersonResponses, UpdatePersonErrors, ThrowOnError> => (options.client ?? client).put<UpdatePersonResponses, UpdatePersonErrors, ThrowOnError>({
    url: '/api/persons/{tmdbId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createActor = <ThrowOnError extends boolean = false>(options: Options<CreateActorData, ThrowOnError>): RequestResult<CreateActorResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateActorResponses, unknown, ThrowOnError>({
    url: '/api/actors',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const addDirectorLabel = <ThrowOnError extends boolean = false>(options: Options<AddDirectorLabelData, ThrowOnError>): RequestResult<AddDirectorLabelResponses, AddDirectorLabelErrors, ThrowOnError> => (options.client ?? client).put<AddDirectorLabelResponses, AddDirectorLabelErrors, ThrowOnError>({ url: '/api/persons/{tmdbId}/director', ...options });

export const getMovies = <ThrowOnError extends boolean = false>(options?: Options<GetMoviesData, ThrowOnError>): RequestResult<GetMoviesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMoviesResponses, unknown, ThrowOnError>({ url: '/api/movies', ...options });

export const expandGraphNode = <ThrowOnError extends boolean = false>(options: Options<ExpandGraphNodeData, ThrowOnError>): RequestResult<ExpandGraphNodeResponses, ExpandGraphNodeErrors, ThrowOnError> => (options.client ?? client).get<ExpandGraphNodeResponses, ExpandGraphNodeErrors, ThrowOnError>({ url: '/api/graph/expand/{label}/{id}', ...options });

export const removeActedInRelation = <ThrowOnError extends boolean = false>(options: Options<RemoveActedInRelationData, ThrowOnError>): RequestResult<RemoveActedInRelationResponses, RemoveActedInRelationErrors, ThrowOnError> => (options.client ?? client).delete<RemoveActedInRelationResponses, RemoveActedInRelationErrors, ThrowOnError>({ url: '/api/persons/{tmdbId}/acted-in/{movieTmdbId}', ...options });

export const addActedInRelation = <ThrowOnError extends boolean = false>(options: Options<AddActedInRelationData, ThrowOnError>): RequestResult<AddActedInRelationResponses, AddActedInRelationErrors, ThrowOnError> => (options.client ?? client).put<AddActedInRelationResponses, AddActedInRelationErrors, ThrowOnError>({
    url: '/api/persons/{tmdbId}/acted-in/{movieTmdbId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
