// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ActedInDto = {
    person: string;
    movie: string;
    roles?: null | Array<string>;
};

export type CreatePersonDto = {
    tmdbId: string;
    name: string;
    born?: null | string;
};

export type DbHealthDto = {
    address: string;
    agent: string;
    protocolVersion: string;
};

export type EdgeDto = {
    id: string;
    source: string;
    target: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
};

export type GraphPayloadDto = {
    nodes: Array<NodeDto>;
    edges: Array<EdgeDto>;
};

export type MovieDto = {
    tmdbId: string;
    movieId: string;
    title: string;
    year?: null | number | string;
    plot?: null | string;
    poster?: null | string;
    imdbRating?: null | number | string;
    genres?: null | Array<string>;
};

export type MovieProfileDto = {
    title: string;
    year?: null | number | string;
    directors?: null | Array<string>;
    avgRating?: null | number | string;
    actors?: null | Array<string>;
};

export type NodeDto = {
    id: string;
    businessKey: null | string;
    labels: Array<string>;
    properties: {
        [key: string]: unknown;
    };
};

export type PaginatedResultDtoOfMovieDto = {
    items: Array<MovieDto>;
    totalCount: number | string;
    skip: number | string;
    take: number | string;
};

export type PersonDto = {
    tmdbId: string;
    name: string;
    born?: null | string;
    labels?: null | Array<string>;
};

export type PersonProfileDto = {
    name: string;
    born?: null | string;
    actedIn?: null | Array<string>;
    directed?: null | Array<string>;
};

export type RolesDto = {
    roles: Array<string>;
};

export type UpdatePersonDto = {
    name: string;
    born?: null | string;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type HealthDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/db';
};

export type HealthDbResponses = {
    /**
     * OK
     */
    200: DbHealthDto;
};

export type HealthDbResponse = HealthDbResponses[keyof HealthDbResponses];

export type GetApiDebugBrokenQueryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/broken-query';
};

export type GetApiDebugBrokenQueryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiDebugDuplicateGenreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/duplicate-genre';
};

export type GetApiDebugDuplicateGenreResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTopMoviesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number | string;
    };
    url: '/api/movies/top';
};

export type GetTopMoviesResponses = {
    /**
     * OK
     */
    200: Array<MovieDto>;
};

export type GetTopMoviesResponse = GetTopMoviesResponses[keyof GetTopMoviesResponses];

export type GetMovieProfileData = {
    body?: never;
    path?: never;
    query: {
        title: string;
    };
    url: '/api/movies/profile';
};

export type GetMovieProfileErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMovieProfileResponses = {
    /**
     * OK
     */
    200: MovieProfileDto;
};

export type GetMovieProfileResponse = GetMovieProfileResponses[keyof GetMovieProfileResponses];

export type DeletePersonData = {
    body?: never;
    path: {
        tmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}';
};

export type DeletePersonErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeletePersonResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePersonResponse = DeletePersonResponses[keyof DeletePersonResponses];

export type GetPersonProfileData = {
    body?: never;
    path: {
        tmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}';
};

export type GetPersonProfileErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetPersonProfileResponses = {
    /**
     * OK
     */
    200: PersonProfileDto;
};

export type GetPersonProfileResponse = GetPersonProfileResponses[keyof GetPersonProfileResponses];

export type UpdatePersonData = {
    body: UpdatePersonDto;
    path: {
        tmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}';
};

export type UpdatePersonErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdatePersonResponses = {
    /**
     * OK
     */
    200: PersonDto;
};

export type UpdatePersonResponse = UpdatePersonResponses[keyof UpdatePersonResponses];

export type CreateActorData = {
    body: CreatePersonDto;
    path?: never;
    query?: never;
    url: '/api/actors';
};

export type CreateActorResponses = {
    /**
     * Created
     */
    201: PersonDto;
};

export type CreateActorResponse = CreateActorResponses[keyof CreateActorResponses];

export type AddDirectorLabelData = {
    body?: never;
    path: {
        tmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}/director';
};

export type AddDirectorLabelErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type AddDirectorLabelResponses = {
    /**
     * OK
     */
    200: PersonDto;
};

export type AddDirectorLabelResponse = AddDirectorLabelResponses[keyof AddDirectorLabelResponses];

export type GetMoviesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
        search?: string;
    };
    url: '/api/movies';
};

export type GetMoviesResponses = {
    /**
     * OK
     */
    200: PaginatedResultDtoOfMovieDto;
};

export type GetMoviesResponse = GetMoviesResponses[keyof GetMoviesResponses];

export type ExpandGraphNodeData = {
    body?: never;
    path: {
        label: string;
        id: string;
    };
    query?: never;
    url: '/api/graph/expand/{label}/{id}';
};

export type ExpandGraphNodeErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ExpandGraphNodeResponses = {
    /**
     * OK
     */
    200: GraphPayloadDto;
};

export type ExpandGraphNodeResponse = ExpandGraphNodeResponses[keyof ExpandGraphNodeResponses];

export type RemoveActedInRelationData = {
    body?: never;
    path: {
        tmdbId: string;
        movieTmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}/acted-in/{movieTmdbId}';
};

export type RemoveActedInRelationErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RemoveActedInRelationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveActedInRelationResponse = RemoveActedInRelationResponses[keyof RemoveActedInRelationResponses];

export type AddActedInRelationData = {
    body: RolesDto;
    path: {
        tmdbId: string;
        movieTmdbId: string;
    };
    query?: never;
    url: '/api/persons/{tmdbId}/acted-in/{movieTmdbId}';
};

export type AddActedInRelationErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type AddActedInRelationResponses = {
    /**
     * OK
     */
    200: ActedInDto;
};

export type AddActedInRelationResponse = AddActedInRelationResponses[keyof AddActedInRelationResponses];
